-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public."Service"
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    name text COLLATE pg_catalog."default" NOT NULL DEFAULT ''::text,
    description text COLLATE pg_catalog."default",
    CONSTRAINT "Service_pkey" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Service"
    OWNER to postgres;

ALTER TABLE IF EXISTS public."Service"
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public."Service" TO anon;

GRANT ALL ON TABLE public."Service" TO authenticated;

GRANT ALL ON TABLE public."Service" TO postgres;

GRANT ALL ON TABLE public."Service" TO service_role;

COMMENT ON TABLE public."Service"
    IS 'Service table';
