name: CI

on:
  push:
    branches:
      - main
      - feat/*
      - chore/*
      - fix/*
      - docs/*
    
  pull_request:
    branches:
      - main

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install
        run: pnpm i
      - name: Run unit tests with coverage
        run: pnpm coverage
      - uses: codecov/codecov-action@v3
        with: 
          flags: unittests